# Generated by Django 4.1.13 on 2023-12-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_delete_review'),
        ('BookAuthor', '0002_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='SellerAdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newseller'),
        ),
    ]
