# Generated by Django 4.1.13 on 2023-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Street', models.CharField(max_length=30)),
                ('Address', models.TextField(unique=True)),
                ('Zipcode', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('PhnCode', models.CharField(max_length=20)),
                ('PhnNumber', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
