# Generated by Django 4.1.13 on 2023-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.TextField(unique=True)),
                ('Registername', models.CharField(max_length=30)),
                ('AuthorLicno', models.CharField(max_length=30)),
                ('Proof1', models.FileField(upload_to='Authorlicproof/')),
                ('Proof2', models.FileField(upload_to='Authoridentyproof/')),
                ('Password', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
