# Generated by Django 4.1.13 on 2023-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_newseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseller',
            name='AuthorLicno',
            field=models.CharField(max_length=20),
        ),
    ]
