# Generated by Django 4.1.13 on 2023-12-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
    ]
