# Generated by Django 4.1.13 on 2023-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_remove_complaint_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Delivery', 'Delivery'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
