# Generated by Django 4.1.13 on 2023-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_complaint_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseller',
            name='Proof1',
            field=models.FileField(upload_to='auth_license/'),
        ),
        migrations.AlterField(
            model_name='newseller',
            name='Proof2',
            field=models.FileField(upload_to='author_proof/'),
        ),
    ]
