# Generated by Django 4.1.13 on 2023-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_newseller_proof1_alter_newseller_proof2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseller',
            name='Proof1',
            field=models.ImageField(upload_to='auth_license/'),
        ),
        migrations.AlterField(
            model_name='newseller',
            name='Proof2',
            field=models.ImageField(upload_to='author_proof/'),
        ),
    ]
