# Generated by Django 4.1.13 on 2023-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_newseller_proof1_alter_newseller_proof2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseller',
            name='vstatus',
            field=models.IntegerField(default=0),
        ),
    ]
