# Generated by Django 4.1.13 on 2023-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_newseller_vstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseller',
            name='Proof1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newseller',
            name='Proof2',
            field=models.CharField(max_length=20),
        ),
    ]
