# Generated by Django 4.1.13 on 2023-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_newseller_proof1_alter_newseller_proof2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseller',
            name='Proof1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newseller',
            name='Proof2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
