# Generated by Django 4.1.13 on 2023-12-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuthor', '0002_ebook'),
        ('Guest', '0013_alter_newseller_proof1_alter_newseller_proof2'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Bookdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookAuthor.book'),
        ),
    ]
