# Generated by Django 4.1.13 on 2023-12-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_review_bookdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
