# Generated by Django 4.1.13 on 2023-12-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_alter_newseller_proof1_alter_newseller_proof2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
