# Generated by Django 4.1.13 on 2023-12-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
