# Generated by Django 4.1.13 on 2023-12-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_newseller_vstatus'),
        ('BookAuthor', '0002_ebook'),
        ('User', '0003_remove_cart_booking_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking1_Date', models.DateField(auto_now=True)),
                ('b1_status', models.IntegerField(default=False)),
                ('p_status', models.IntegerField(default=False)),
                ('Bookbooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookAuthor.book')),
                ('User1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newuser')),
            ],
        ),
    ]
