# Generated by Django 4.1.13 on 2023-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_cart_b1_status_alter_cart_p_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='b1_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='p_status',
            field=models.BooleanField(default=True),
        ),
    ]
