# Generated by Django 4.1.13 on 2023-12-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuthor', '0002_ebook'),
        ('User', '0006_alter_cart_b1_status_alter_cart_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='EBookbooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookAuthor.ebook'),
        ),
    ]
