# Generated by Django 4.1.13 on 2023-12-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuthor', '0003_book_selleradd'),
        ('User', '0007_cart_ebookbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')])),
                ('comment', models.TextField()),
                ('Bookdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookAuthor.book')),
            ],
        ),
    ]
