# Generated by Django 4.1.13 on 2023-12-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_delete_review'),
        ('User', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newseller'),
        ),
    ]
