# Generated by Django 4.1.13 on 2023-12-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuthor', '0004_ebook_sellereadd'),
        ('User', '0009_cart_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='EBookdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookAuthor.ebook'),
        ),
    ]
